// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vytsosxzdcsgfexenoob.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ5dHNvc3h6ZGNzZ2ZleGVub29iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3OTExOTksImV4cCI6MjA2MTM2NzE5OX0.kX9YKhE9p8tIKkTUWVKwe4UXk0hf-yeUpq0RceaQ0_g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);